### PR TITLE
Proposal: Custom folder covers/thumbnails

### PR DESCRIPTION
**Pull request by gmasil**
On my fork I implement whatever comes to my mind, this time it is custom folder covers and I thought it might be interesting for others.

**Current situation:**
Usually the first image inside a folder will determine its thumbnail, you can change the thumbnail by changing the sorting inside a folder. So for example if you want a particular image to be your folder cover you could sort by name and make sure this file will come first (e.g. AAAA_my_image.png).

**Proposal:**
Rename the file you want to be your folder cover to cover.png (or webp, jpeg, mp4 etc.) and it will be automatically used as your folders thumbnail. Additionally it will be moved to be the first image inside this folder, so it is easier to find. This is currently hardcoded, but can be made optional through a settings checkbox if desired.

What is missing:
* only certain file types can be used, this should be implemented more flexible
* maybe we want a settings option to enable/disable this feature and/or the resorting of folder contents
* performance impact should be small, but is not taken into account, yet

### CODE REVIEW

**Comment by Aga-C** [comment]
What about long tapping the folder -> three dots menu -> `Change cover` -> `Use default`?

**Comment by Aga-C** [comment]
What about long tapping the folder -> three dots menu -> `Change cover image` -> `Select photo`?

**Comment by gmasil** [comment]
Yeah that's a good and easy way :)
I didn't know about it, do we have a full feature list?
I keep uninstalling the app during testing and stuff, so I'll stick to my solution as folder covers survive this way, but for everyone else this is just perfect.
Closing now.

**Comment by Aga-C** [comment]
> do we have a full feature list?

No, we don't have. I think it's better to make PRs regarding accepted issues from this repository, eventually also issues raised in SMT :)

**Comment by inson1** [comment]
btw feature list wouldnt be bad idea

**Comment by naveensingh** [comment]
Yes, documentation, feature lists, etc. will all be added slowly as Fossify matures.

**Pull request closed without merging**
