### PR TITLE
Fix slideshow

### LINKED ISSUE #35: The slideshow doesn't work
**Checklist**
 - [x] I can reproduce the bug with the latest version. 
 - [x] I made sure that there are no existing issues - open or closed - to which I could contribute my information to.
 - [x]  I have read the FAQ and my problem isn't listed.
 - [x]  I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
 - [x]  This issue contains only one bug.
 - [x]  I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

**Describe the bug**
The slideshow doesn't work. Only the first image of a folder is shown. Changing the slideshow options in the slideshow-dialogue doesn't change anything.

**To Reproduce**
1. Select a folder with more than 1 image 
2. Go to the 'Main menue'
3. Click on '...' (the three points)
4. Click on 'Slideshow' 
5. Setup the slideshow options
6. Click on 'OK'
 7. See error: Only the first image of a folder is shown. No slideshow is active. There's no switch to another image  

**Describe the bug**
The slideshow doesn't work. Only the first image of a folder is shown. Changing the slideshow options in the slideshow-dialogue doesn't change anything.

**Expected behavior**
With the slideshow an automatically switch to images in a selected folder should be made. The chosen options in the slideshow-dialogue, that is shown when 'Slideshow' is clicked in the main menu, should be applied.

**Screenshots**

**Device info (please complete the following 
information):**
 - Model: Pixel Pro 7
 - OS: Android 14
 - Version 1.02

**Additional context**

### PR DESCRIPTION
**Pull request by gmasil**
_This PR was originally created here: https://github.com/SimpleMobileTools/Simple-Gallery/pull/3043_

Currently the slideshow is not working, see https://github.com/SimpleMobileTools/Simple-Gallery/issues/3020.

When the slideshow is starting the `ViewPagerActivity` is activated and will call `initContinue()` where `checkSystemUI()` is called. This will stop the slideshow immediately if the activity is not in fullscreen mode.

I removed the call to `stopSlideshow()`.

Edit: Resolves #35

### CODE REVIEW

**Comment by naveensingh** [comment]
@gmasil as per the SMT reports, it looks like this bug only appears on Android 14?

**Comment by Aga-C** [comment]
@naveensingh I can confirm this bug (checked on emulator) on Android 14. On Android 13 everything works fine.

**Comment by naveensingh** [comment]
@gmasil with this solution, the slideshow can no longer be stopped by taping on the currently visible image.

The slideshow is being stopped because the `mIsFullScreen` variable is false when it should be true. The first call to `hideSystemUi()` doesn't seem to work properly on Android 14. That's the root cause. The API we are using was deprecated some time ago. I'll investigate this later.

**Comment by gmasil** [comment]
> @gmasil with this solution, the slideshow can no longer be stopped by taping on the currently visible image.
> 
> The slideshow is being stopped because the `mIsFullScreen` variable is false when it should be true. The first call to `hideSystemUi()` doesn't seem to work properly on Android 14. That's the root cause. The API we are using was deprecated some time ago. I'll investigate this later.

Oh I didn't know that you could stop the slideshow by tapping. I'll try to investigate further, thanks!

**Comment by Goodwy** [comment]
The isInMultiWindowMode condition does not work. It works if you replace the code

```
mIsFullScreen = if (isNougatPlus() && isInMultiWindowMode) {
                visibility and View.SYSTEM_UI_FLAG_LOW_PROFILE != 0
            } else if (visibility and View.SYSTEM_UI_FLAG_LOW_PROFILE == 0) {
                false
            } else {
                visibility and View.SYSTEM_UI_FLAG_FULLSCREEN != 0
            }
```
by

```
mIsFullScreen = if (isUpsideDownCakePlus()) {
                visibility and View.SYSTEM_UI_FLAG_LOW_PROFILE != 0
            } else if (isNougatPlus() && isInMultiWindowMode) {
                visibility and View.SYSTEM_UI_FLAG_LOW_PROFILE != 0
            } else if (visibility and View.SYSTEM_UI_FLAG_LOW_PROFILE == 0) {
                false
            } else {
                visibility and View.SYSTEM_UI_FLAG_FULLSCREEN != 0
            }
```

**Comment by gmasil** [comment]
@Goodwy thanks a lot, this seems to be working.
Updated PR, Testers are welcome again :)

**Comment by naveensingh** [comment]
These PRs are being closed automatically by GitHub or some glitch. I'm not closing them.

**Comment by naveensingh** [comment]
@gmasil 

I [detached](https://github.com/FossifyOrg/General-Discussion/issues/84) all the forked Fossify repositories and as a result, PRs originating from SMT forks are being closed automatically. Please consider the following solution:
 -  Fork the new repository from Fossify.
 - Add your SMT fork as a remote and merge your changes.
 - Raise a new PR using the newly forked Fossify repository.

Sorry for the inconvenience.

**Comment by gmasil** [comment]
Now that @Goodwy provided the solution he/she might as well have the honor.
I used this since Jan 18 and I haven't noticed any problems so far, so green light from my side.

**Pull request closed without merging**
