### PR TITLE
Rename package names

### PR DESCRIPTION
**Pull request by naveensingh**
### Changes:
 - Rename package name to `org.fossify.gallery`
 - Replace SMT links with Fossify equivalents.
 - Set up custom domain for Jitpack. Now we can include commons and other libs using just `org.fossify:commons:tag`.
 - Reset app version to 1.0.0
 - Update the main app icon.
 - Remove old release notes.

**TODO**: Fix app icon color customization.

### CODE REVIEW

**Comment by gmasil** [comment]
Maybe we should resolve existing PRs from original repo first, otherwise we get lots of extra work. Just an idea.

**Comment by naveensingh** [comment]
@gmasil that's a good idea but I want to release a few apps as soon as possible, reviewing and testing those changes will slow us down. It's not just one PR.

**Comment by gmasil** [comment]
Its a valid point. Refactoring the PRs will not be too bad, but I wanted to propose it.
So should I redirect my PRs to here and wait for the refactoring to be done?

**Comment by naveensingh** [comment]
@gmasil Sure. You can move your PRs here whenever you want but they will be reviewed and merged only after the initial release. There will probably be a lot of conflicts so I would suggest you redo it after the release.

**Pull request merged**
